### ISSUE TITLE
Minor typo in resolve_repobee_pip_uri function of install.sh

### ISSUE THREAD

**Issue by spapadim** [repobee/repobee#1116]
First off, thanks for writing this tool and making it available!

On recent install attempt, I wanted to use `master` branch, but `install.sh master` failed with invalid URL (due to trailing `@` without tag). I suspect [line 220 of `scripts/install.sh`](https://github.com/repobee/repobee/blob/master/scripts/install.sh#L220) should be changed to

```diff
-            repobee_pip_uri="git+$REPOBEE_HTTPS_URL.git@$version"
+            repobee_pip_uri="git+$REPOBEE_HTTPS_URL.git@$1"
```
since `$version` is not defined in the `resolve_repobee_pip_uri` function.

---
FWIW, this was encountered after trying to install default (which currently is `v3.8.0` tag) using python=3.11.1 via pyenv (on Ubuntu 20.04 LTS). In that case, venv gets created but then the `$HOME/env/bin/pip install --upgrade 'git+https://github.com/repobee/repobee.git@v3.8.0'` command fails, with some sort of syntax error on the  [`"dataclasses>='0.7';python_version<'3.7'"` setup requirement spec](https://github.com/repobee/repobee/blob/v3.8.0/setup.py#L87).

Did not investigate further, as `master` (which drops 3.7 support and the apparently offending requirement) installed just fine.

**Comment by slarse** [comment]
Hi @spapadim,

> On recent install attempt, I wanted to use master branch, but install.sh master failed with invalid URL (due to trailing @ without tag). I suspect [line 220 of scripts/install.sh](https://github.com/repobee/repobee/blob/master/scripts/install.sh#L220) should be changed to

You are absolutely right. Looking over the install script I found a number of more issues, I will upload an improved version shortly.

> FWIW, this was encountered after trying to install default (which currently is v3.8.0 tag) [.. ] Did not investigate further, as master (which drops 3.7 support and the apparently offending requirement) installed just fine.

Oof, that's not good, the primary install path isn't working for the currently released version. That version specifier should not have single quotes around `'0.7'`, I don't understand how that ever worked :s.

I will make a new release ASAP.

**Comment by slarse** [comment]
I've released RepoBee v3.8.1 which can actually be installed with the current install script, making fixing it a little bit less urgent. The install script will follow sometime tonight. I obviously need a periodic CI job that ensures that the installer can actually run on the current release...

Thanks for making this problem known to me @spapadim !

**Comment by slarse** [comment]
Turns out I'd thought ahead at some point and already have tests for the latest release, the scheduled weekly tests failed miserably this weekend. Something in the cosmos changed such that the invalid syntax in that requirement was actually caught to be invalid.

**Comment by slarse** [comment]
Hi @spapadim ,

Thanks for reporting the issue. I've updated the install script fixing the bug you highlighted and made some other general improvements to it.
