### ISSUE TITLE
How to delete repos created by repobee (800 repos!)

### ISSUE THREAD

**Issue by connorferster** [repobee/repobee#1133]
Hi there!

I am in desperate need of assistance. How can I use the CLI tool to delete all of these repos?

**Comment by rjglasse** [comment]
First, I've managed to do the same with a wild regex. Second, there is not a specific command, but the GitHub API has an endpoint for that: https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#delete-a-repository

It might just be the case of a python script to iterate over the list of 800.

**Comment by connorferster** [comment]
Thanks @rjglasse 

I ended up [finding this](https://josh-ops.com/posts/github-script-to-delete-repos/) and was able to make quick work. Very convenient!

**Comment by slarse** [comment]
Hi @connorferster,

Glad you got it to work out.

I deliberately never added a "delete" command as I found that to be a little bit of danger territory. It's not at all hard to implement so perhaps adding it would be worthwhile, seeing how both you and @rjglasse have apparently had need of it.

Should I take it as a feature request?

**Comment by rjglasse** [comment]
Whilst it is ultra rare, it feels like yes, this is perhaps a nice feature to have. Maybe there needs to be a subcommand like `danger` so it never gets used accidentally, or some warning dialogue if it is to be under the `repos` subcommand :)
