### ISSUE TITLE
Plugin subcommand has disappeared in v3.8.1

### ISSUE THREAD

**Issue by rjglasse** [repobee/repobee#1142]
Here is what it looks like for a fresh install:

![image (3)](https://user-images.githubusercontent.com/4233865/229054743-9c8f093c-ed99-4b1d-ae92-d9c277531cd6.png)

**Comment by slarse** [comment]
I will try to fix the install script later tonight but regardless of that anyone who installed RepoBee with that bad version of the install script will unfortunately need to remove the `.repobee` directory and then reinstall :/

**Comment by slarse** [comment]
Fixed in #1144.

@rjglasse Any of your TAs that installed RepoBee with the bad install script need to remove the `~/.repobee` directory and install again. Oopsie.
