### ISSUE TITLE
GitHub secondary rate limit still acting up

### ISSUE THREAD

**Issue by slarse** [repobee/repobee#1199]
Bug report from user by email, they are still being hit by GitHub's secondary rate limit (see #991 and #1065).

So the previous patches didn't quite do it. Fortunately PyGithub supports secondary rate limit mitigation as of September 2023 so that ought to do the trick.

**Comment by dbosk** [comment]
26th August 2024:
```
[ERROR] PlatformError: 403 {"documentation_url":
"https://latest/rest/overview/rate-limits-for-the-rest-api#about-secondary-rat
e-limits", "message": "You have exceeded a secondary rate limit. Please wait a
few minutes before you try again. If you reach out to GitHub Support for help,
please include the request ID 89087771-4cf6-4a75-95c1-9033345da521."}
```
But it's more rare now. Only happened once this year.

**Comment by dbosk** [comment]
I should add that maybe the repobee version was before this issue closed. No idea when I last rebuilt my docker image. Anyway, it happens rarely now, even though I cloned ~800 repos every half hour around that time.

**Comment by slarse** [comment]
Hey,

You might've been running with my home grown rate limiting which didn't quite work. The newer rate limiting that went into RepoBee 3.10 (that was released in August) is implemented by the underlying GitHub API library and should be much more finely tuned than my attempt was.
