### ISSUE TITLE
Ability to clone data posted on Issue Tracker / Other Github data of interest

### ISSUE THREAD

**Issue by rjglasse** [repobee/repobee#138]
Just like the clone feature, it would be good to be able to programmatically clone other data that is associated with the repo on the Github interface. The best example would be a clone of the issue tracker. The main two motivations are (1) data preservation and (2) convenience for offline analytics for pedagogical research. I imagine it follows the same API as repomate:

`repomate clone-issues -mn week-X -sf students.txt -status [all | open | closed ] -filter [regex]`

Food for thought :)

**Comment by slarse** [comment]
You mean like `list-issues` but saving the files?

**Comment by rjglasse** [comment]
:) perfect! I'm off to RTFM :)

**Comment by slarse** [comment]
Well, `list-issues` only lists issues currently (optionally with the body), and that does not include comments. It's mostly meant to be used for quickly checking which issues exist for just a few students/weeks, and sometimes what's written in them (for example if you want to check the feedback given to some students). It's not well suited for large queries as the output will be a bit hard to read, and the fact that the REST api requires one to make at least two queries per repo to get all issues.

There's definitely a use-case for being able to save all issues together with all related comments, in a local database (maybe just a JSON file). Two key difficulties come to mind.

1. With PyGithub (using the REST API), querying for all issues and comments for `N` different repositories requires a minimum of some `2*N` queries (one query for the repo, at least one query for the issues related to it).
2. If we also want the comments for each issue, then that's +1 query for each issue that's found.

If you do that at a large scale (say a couple of hundred repos with a few issues each), that's gonna be thousands of queries.

This could potentially be implemented with just one or two queries to the GraphQL API, though, but that requires some extra stuff that's not particularly relevant to the core of Repomate. One way forward may be to split the data sciency functionality off into a separate GraphQL-dependent part, and extend the plugin system such that it can be seamlessly integrated with Repomate.

**Comment by rjglasse** [comment]
Yup, I have some sketchy scripts that just used the Python `requests` library and the API endpoints :-\ and there was a fair wait for 12 weeks of issues x 140 ish active students :)

Agree that this is not core, but the use case for analytics is still strong, and decent excuse to dive into GraphQL API. Perhaps a longer discussion on that could be good to have :)

**Comment by slarse** [comment]
Yes, we could definitely have a look at more use-cases. I think the gathering of issues/comments itself is a strong one. If we can find some more use-cases where there is a demand for extensive data gathering that does not involve cloning repos, then we could warrant an excursion into the GraphQL API.

I think extending the plugin system enough to allow for new top-level commands really wouldn't be too hard, so it would be feasible to create a separate data science plugin for Repomate.

**Comment by slarse** [comment]
This is pretty much covered by the `--hook-results-file` option to `list-issues`.

The now relevant topic is what data to fetch for issues, see #329
