### ISSUE TITLE
add video on README

### ISSUE THREAD

**Issue by monperrus** [repobee/repobee#396]
Ric is showing a great video about repobee.

It could be added to the README, as in https://github.com/rectorphp/rector

**Comment by slarse** [comment]
Thanks for the tip, Martin! I was actually considering doing that, but whenever I've created GIF-files in the past they've just become very large (on the order of megabytes for ~30 second GIFs). I don't recall precisely how long the video Ric showed is, but it's at least in the 5-minute range, so it would get pretty large.

But it'd definitely be a good thing show off in the repo, I'll see what I can do!
