### ISSUE TITLE
There's always an empty log line for each command

### ISSUE THREAD

**Issue by slarse** [repobee/repobee#423]
Not sure where it's coming from, but it's a little bit annoying. It just looks like this at the very end of the log output:

```
[INFO]
```

**Comment by tohanss** [comment]
When testing sanitize-repo, instead of getting just [INFO], i got 

`[INFO] hook results for sanitize-repo`

As the last output, is this related?

**Comment by slarse** [comment]
Do you not also get the reported results? I.e. the message and status?

**Comment by tohanss** [comment]
Yes i got those, i just meant that this one was there instead of just [INFO]

**Comment by slarse** [comment]
Ah, okay. But yes, its related. Extensions that don't return a result cause the empty line.

**Comment by slarse** [comment]
It's this part of the code:

https://github.com/repobee/repobee/blob/07c29c3f604f7046778af190322f739cb638890a/src/_repobee/cli/dispatch.py#L58-L63

**Comment by slarse** [comment]
@tohanss Wanna try and change that, then play around with it and see if it works out?

**Comment by slarse** [comment]
@tohanss Don't forget about this one :)

**Comment by tohanss** [comment]
Im actually going to try fixing this now :)
