### ISSUE TITLE
Add missing command for pre-commit

### ISSUE THREAD

**Issue by tohanss** [repobee/repobee#432]
https://repobee.readthedocs.io/en/stable/contributing.html#pre-commit-hooks

the following section says "In the root of the project, run:", but does not give a command to run

**Comment by slarse** [comment]
The directive on line 71 of `docs/contributing.rst` is missing a directive. It currently reads:

```
.. code-block::
```
but it should be 
```
.. code-block:: bash
```

Feel free to submit a PR to fix it!
