### ISSUE TITLE
Replace str.format with f-strings

### ISSUE THREAD

**Issue by slarse** [repobee/repobee#460]
> **IMPORTANT:** Doing this for the entire codebase in a single PR would be infeasible to review, and would most likely lead to a large amount of conflicts. Do one module per PR, and reference this issue in the PR (but don't say "fix", just reference the issue).

As we have finally dropped support for Python 3.5, we can now utilize f-strings. It would be a good idea to replace format strings with f-strings, except in the places where we use format strings as templates that are stored in variables. There is a TON of use of `str.format` in the test suite in particular.

So, all instances on the form `"some literal {} string".format(var)` should be replaced with `f"some literal {var} string"`. Here's an example of where we should use an f-string instead.

https://github.com/repobee/repobee/blob/dbb1b1833fa336f33657679b1c7ce6b8350e9cde/tests/unit_tests/repobee/test_command.py#L204-L206

The above should be rewritten as:

```python
description=f"{repo_base_name} created for {student}"
```

> **Finding modules with `str.format` calls:** Simply executing `grep -r \.format` in a shell should net you most occurrences.

### Redundant formatting directives
Some format strings contain the redundant `!s` formatting directive. You _don't_ need to translate that into a `str()` call, as that's implicit. So, for example, the following transformation is perfectly fine:

```python
# original
"hello {!s}!".format(some_obj)

# transformation
f"hello {some_obj}!"
```

**Comment by slarse** [comment]
@tohanss This would be a good issue for you to start poking around the codebase!

**Comment by ShreyaDhananjay** [comment]
Hi can I start working on this?

**Comment by slarse** [comment]
@ShreyaDhananjay Hi and welcome!

You're absolutely welcome to start at this, it would be much appreciated. The worst offenders in using `str.format` in the production code are the [github module](https://github.com/repobee/repobee/blob/master/src/_repobee/ext/defaults/github.py) and the [gitlab module](https://github.com/repobee/repobee/blob/master/src/_repobee/ext/gitlab.py). The test suite also makes extensive use of it.

Since this is such a broad issue, it would be good if you indicate either by a comment in this issue or by PRs which module(s) you're working on.

Ping me if you need any help :)

**Comment by ShreyaDhananjay** [comment]
I'll start working on the github and gitlab modules then. Thanks!

**Comment by slarse** [comment]
@ShreyaDhananjay Excellent!

Oh, and fair warning, `black` is pretty unhelpful when it comes to formatting strings (read: barely helps at all), so you will likely have to do a decent amount of manual formatting in order to satisfy the 79 character line length requirement. Don't hesitate to submit a partially complete PR if you can't quite make that work, and we'll just work it out.

**Comment by ShreyaDhananjay** [comment]
Okay thanks!
