### ISSUE TITLE
Plug-in installer not working

### ISSUE THREAD

**Issue by amaberg** [repobee/repobee#603]
I get this error no matter which plug-in I try to install. 

Am using Ubuntu Bash on WSL. 

![Skärmklipp](https://user-images.githubusercontent.com/52538934/90989642-aa6a3480-e59b-11ea-873a-de723de2e954.JPG)

**Comment by slarse** [comment]
Thanks for the report! I'm fairly certain this is due to an accidental inclusion of Python3.7-specific functionality in the plugin manager, and I'm guessing that you are running Python 3.6.

**Comment by slarse** [comment]
@amaberg I found and fixed the issue, thanks again for the bug report!
