### ISSUE TITLE
Quiet option

### ISSUE THREAD

**Issue by dbosk** [repobee/repobee#625]
It would be nice to have a quiet option that only outputs on errors. This is useful for cronjobs, where you only want to know of failures. E.g. when we have to recreate teams until all students registered on the GitHub instance.

Alternativeley, for version 4.0: follow the UNIX philosophy of silently succeed and noisily fail, so one can add `-v` for verbose output :-)

**Comment by slarse** [comment]
A quiet option is a good idea. As this is aimed at users who may not necessarily be very familiar with anything UNIX (e.g. new TAs), I prefer defaulting to verbosity.

I'll try to add in a `--quiet` option in the coming week, it should be borderline trivial.

**Comment by dbosk** [comment]
Great, thanks! :-D

**Comment by slarse** [comment]
@dbosk I'm considering making `-q|--quiet` a stacking option, up to three times. For example:

* `-q`: Normal application output disabled, but warning and error log messages are still displayed.
* `-qq`: Also disable warning log messages.
* `-qqq`: No output at all, unless there is a crash.

I was thinking of this as there are quite a few warning logs when setting up student repos/creating teams if there are student accounts that don't yet exist. And maybe one doesn't care about that in some situations (such as in your use case), and want to disable it.

Note that warnings and errors still go to the logfile, even when not displayed in the terminal.

**Comment by dbosk** [comment]
Sounds great to me!

**Comment by slarse** [comment]
@dbosk Thanks for this suggestion, it was very easy to implement and is a nice quality of life improvement. It will go out in RepoBee 3.1 which I plan to release this weekend.

**Comment by dbosk** [comment]
Excellent, many thanks! :-)
