### ISSUE TITLE
Cannot setup repos

### ISSUE THREAD

**Issue by rjglasse** [repobee/repobee#626]
When I try to setup repos like this I got the following error:

```
% repobee repos setup --assignments task-1
[ERROR] ValueError: unsupported protocol in 'file:///Users/ric/dev/inda-20/repos/task-1', please use https://
```

Any suggestions?

**Comment by slarse** [comment]
This is caused by having a template repository in the current working directory, as opposed from pulling it from the template organization. I'll have a fix for it tonight.

**Comment by slarse** [comment]
@rjglasse All fixed, thanks for the bug report!
