### ISSUE TITLE
Setup command throws error messages for repos that already have commits

### ISSUE THREAD

**Issue by rjglasse** [repobee/repobee#630]
Scenario - student repos have been created via setup. Students work on repos. Setup command is run again (for latecomers typically), giving this message for some repos that have now had commits made by students:

```
...
[ERROR] Failed to push to https://gits-15.sys.kth.se/inda-20/XXXX-task-1
return code: 1
To https://gits-15.sys.kth.se/inda-20/XXXX-task-1
[WARNING] 13 pushes failed ...
```

Perhaps a nicer message?

**Comment by slarse** [comment]
It appears as if I've inadvertently changed some behavior with setup and update. Setup is trying to push to existing repos, and update is creating repos that don't exist. The two problems are related.
