### ISSUE TITLE
Installer script likely contains superfluous commands in help message

### ISSUE THREAD

**Issue by htdebeer** [repobee/repobee#668]
When running the GNU/Linux installer I did not have "python3-venv" installed. I did get an error message telling me to install that package and explained how. However, I do think the first two command, to add the "universe" to apt and "update" apt are superfluous. I suspect that most users do have "universe" enabled, but just did not install this "python3-venv" package.

Suggestion: Only tell the user how to install "python3-venv" package.

**Comment by slarse** [comment]
I'm not at all well versed with Debian, those commands are there as those were the steps I myself had to go through to get it working on a fresh install of Ubuntu 18.04. So it was my understanding that the universe repository is not always added as a part of installing e.g. Ubuntu.

Does it hurt to add a repository twice? I'm thinking that it may be better to keep those commands as long as they don't do bad things, as they at worst are redundant, and at best save a beginner some headache's.

**Comment by htdebeer** [comment]
No, it does not matter to run that command twice: it will just do nothing.
