### ISSUE TITLE
Add a get_repo function to the platform API

### ISSUE THREAD

**Issue by slarse** [repobee/repobee#672]
I've often found that I need to fetch just one repo, and it's really annoying to have to call `get_repos` for that.

**Comment by tohanss** [comment]
@slarse This could be useful for a get_data function #938, would make that easier

**Comment by slarse** [comment]
Agreed. Note that the current workaround is something like this (without error handling):

```python
repo = `next(iter(api.get_repos(repo_names=[repo_name])))`
```

Which is, let's say, less than ideal.

**Comment by algomaster99** [comment]
In the pursuit of finding issues easier than #903 , I came here. I found that `get_repo` (API for fetching a single repository) has been defined in `APISpec` and has also been implemented in [`GitTeaAPI`](https://github.com/repobee/repobee/blob/master/src/_repobee/ext/gitea.py#L246) and [`GitHubAPI`](https://github.com/repobee/repobee/blob/master/src/_repobee/ext/defaults/github.py#L256). Or is the issue conveying something different from what I am interpreting?

**Comment by slarse** [comment]
@algomaster99 You're right, this seems to already be a thing. It even seems to have been there since before I opened this issue. I've no memory of implementing it. Soooo... This is just a little derp from my part, it seems, we already have a `get_repo` function. We don't have a `get_team` function, though, so that could be added (see #673).
