### ISSUE TITLE
Docker image on Docker Hub

### ISSUE THREAD

**Issue by dbosk** [repobee/repobee#735]
There is an image for testing (`Dockerfile.test`). Can you make an official streamlined image and put it on [Docker Hub](https://hub.docker.com)?

**Comment by dbosk** [comment]
Use case: I automate some stuff, then I'd like to do that automation in a Docker image, that way I can deply it on my Raspberry Pi or my laptop or some other system without much hassle.

**Comment by dbosk** [comment]
`Dockerfile.test`: I don't like `REPOBEE_NO_VERIFY_SSL=true` and `git config --global http.sslVerify false`.

**Comment by slarse** [comment]
@dbosk Right, great idea! I've actually considered this before, but then just deferred it as a problem for future me.

> Dockerfile.test: I don't like REPOBEE_NO_VERIFY_SSL=true and git config --global http.sslVerify false.

That should absolutely not be used in production :). RepoBee will issue a warning on each command if you use `REPOBEE_NO_VERIFY_SSL`, it's only for the GitLab system tests that use a self-signed SSL certificate.

I'd imagine that we need something like this:

```
FROM python:3.8-alpine

RUN apk update
RUN apk add git wget bash

RUN addgroup -S repobee && adduser -S repobee -G repobee
USER repobee
ENV PATH=${PATH}:/home/repobee/.repobee/bin

COPY . /home/repobee/repobee

RUN bash ~/repobee/scripts/install.sh v3.3.0
```

Now there's an obviously silly thing here, namely that the install script will download v3.3.0 and install that. I need to add an option to install from the local repository. In addition, we'll probably want some easy way to specify a config file. Mounting a volume on `/home/repobee/.repobee` will allow for using plugins and such.

What do you think?

**Comment by slarse** [comment]
With alpine, the image is roughly 160 MB, by the way. `buster-slim` is ~300 and `buster` ~900.

**Comment by dbosk** [comment]
On mån 26 okt 2020 11:06:11, Simon Larsén wrote:
> > Dockerfile.test: I don't like REPOBEE_NO_VERIFY_SSL=true and git 
> > config --global http.sslVerify false.
> 
> That should absolutely not be used in production :). RepoBee will 
> issue a warning on each command if you use `REPOBEE_NO_VERIFY_SSL`, 
> it's only for the GitLab system tests that use a self-signed SSL 
> certificate.

Super! :-D

> 
> I'd imagine that we need something like this:
> 
> ```
> FROM python:3.8-alpine
> 
> RUN apk update
> RUN apk add git wget bash
> 
> RUN addgroup -S repobee && adduser -S repobee -G repobee
> USER repobee
> ENV PATH=${PATH}:/home/repobee/.repobee/bin
> 
> COPY . /home/repobee/repobee
> 
> RUN bash ~/repobee/scripts/install.sh v3.3.0
> ```
> 
> Now there's an obviously silly thing here, namely that the install 
> script will download v3.3.0 and install that. I need to add an option 
> to install from the local repository.

:-D

> In addition, we'll probably want some easy way to specify a config 
> file. Mounting a volume on `/home/repobee/.repobee` will allow for 
> using plugins and such.
> 
> What do you think?

Indeed. That's crucial. I think mounting a volume like that is the best 
solution. Then we get access to tokens/keys for accessing GitHub too.

**Comment by dbosk** [comment]
On mån 26 okt 2020 11:07:08, Simon Larsén wrote:
> With alpine, the image is roughly 160 MB, by the way. `buster-slim` is ~300 MB and `buster` ~900 MB.

That's a nice and lightweight image. Particularly if one compares to the 
3+GB that's needed to put a TeX installation in an image :-D

In these situations I like to think back on how things were when I had a 
56k dial-up modem connection.

**Comment by slarse** [comment]
@dbosk Got a PR #737 with a draft for the Dockerfile. Any thoughts on that?

**Comment by dbosk** [comment]
That should be useful. Sorry for the looooonnng turnaround time.
