### ISSUE TITLE
Docs for "Deactivate plugins" could be more explicit

### ISSUE THREAD

**Issue by LinusOstlund** [repobee/repobee#759]
Refering the the documentation for [plugins](https://repobee.readthedocs.io/en/stable/plugins.html#activate-plugins), I'm missing a header for how to deactivate plugins once they're permanently checked.

**Comment by slarse** [comment]
I agree, you almost have to read between the lines right now.

**Comment by slarse** [comment]
@LinusOstlund thanks for reporting this!
