### ISSUE TITLE
Config verify doesn't verify students file

### ISSUE THREAD

**Issue by Inomares** [repobee/repobee#763]
Despite being part of the config wizard (and as such IMO one of the "essential" properties), when running `repobee config verify`, no errors are reported even if the path to the students file is incorrect, or presumably also if the file has incorrect format.

**Comment by slarse** [comment]
It absolutely should verify the config file. It'd be a pretty simple thing to add.

**Comment by slarse** [comment]
Thanks for reporting this. `config verify` now checks that the students file exists, and screams bloody murder if it doesn't.

As there isn't much structure to the file (you can put virtually anything on each line), there's not much to be done in terms of checking its "formatting". In RepoBee 4, the students file will probably be more structured (think yaml), and then it will be relevant to check it's formatting.
