### ISSUE TITLE
Add a dry-run or mock command-line option for developing and testing plugins without doing anything on git

### ISSUE THREAD

**Issue by htdebeer** [repobee/repobee#770]
Would it be possible to have some sort of "dry-run" or "mock" command-line option that would simulate running the command? This would be great for development of custom plugins. For example, while working on a post_setup hook I often make errors in my own code and each time I test my work, a new git repository is being created. However, to debug, fix, and test my hook, each time I first have to remove the previously created repository. If I could "dry run" the setup command, though, I could debug, fix, and test my hook without creating a (new) repository.

**Comment by slarse** [comment]
That would be possible, but what would probably be more helpful to you is a test environment. There are two pretty good options. First, there are built in pytest test fixtures in RepoBee that simulate a hosting platform, and you can use these to quite easily set up automated tests. Unfortunately, this is not yet very well documented in terms of usage, [this is all I've got so far](https://repobee.readthedocs.io/en/stable/repobee_testhelpers/index.html).

The other option would be to setup a local GitLab instance. You could use RepoBee's system test setup for that, [which is fairly well documented](https://github.com/repobee/repobee/tree/master/system_tests). That gives you a local GItLab instance that can be reset in ~30 seconds to some initial state.

What's not relevant yet but might be in the future is using a Gitea instance, which I'm work on support for (#732).

If you just want to fiddle with your plugin a bit and try stuff out, then the local GitLab instance is probably the most flexible solution available right now.

What do you think?

**Comment by htdebeer** [comment]
Your suggestions make sense. At least, they would if I would have approached the development of my Canvas plugin in a more professional way :-) Now I just hack on it whenever I have a spare moment, so setting up my development environment does not have the highest priority. 

As a workaround, I have been using the `post_clone` hook to test the functionality of the `post_setup` hook for as so far I did not need to test the actual integration of gitlab + repobee, but was working on the integration of repobee + Canvas. That works quite well, so that's why I submitted this request.

I'll close the issue and look into your suggestions. Thanks for the quick answer!

**Comment by slarse** [comment]
I really recommend you try setting up a local GitLab instance. It's a bit fiddly the first time you do it, but once you know how to do it it is very easy. You have admin powers on it, and so can add however many students you'd like.

A _super_ neat feature of being an admin on GitLab is that you can "impersonate" a user to see what the platform looks like from their perspective. I used this a lot when tuning students' permissions.

I think the documentation should be sufficient, but do let me know if you get stuck!
