### ISSUE TITLE
Gitlab access stopped working

### ISSUE THREAD

**Issue by htdebeer** [repobee/repobee#774]
This is probably an issue at my end, but suddenly RepoBee started complaining about

```
[ERROR] either organization git-for-assignments-course2020 could not be found, or the base url 'https://gitlab.tue.nl' is incorrect
```

while running the `setup` or `clone` commands. As I did not update my gitlab settings for the past couple of weeks, this is odd. I checked also with command `repobee -p gitlab config verify`, but it gives similar feedback:

```
GitLabAPI is verifying settings ...
Authenticating connection to https://gitlab.tue.nl...
SUCCESS: Authenticated as XXXXXX at https://gitlab.tue.nl
Trying to fetch group git-for-assignments-course2020
[ERROR] NotFoundError: Could not find group with slug git-for-assignments-course2020. Verify that you have access to the group, and that you've provided the slug (the name in theaddress bar).
[ERROR] A plugin exited with an error
```

I do not understand what is happening: clearly I can still log into gitlab and I do have access to this group via both web and API, it seems. Have you any idea what might be going on?

**Comment by slarse** [comment]
The first thing that comes to mind is that `git-for-assignments-course2020` isn't actually the slug of the group (the slug is what you see in the url, it can be different from the name). The only other thing I can think of is that the token doesn't have access privileges to the group.

**Comment by slarse** [comment]
Which version of GitLab are you running (i.e. the platform instance, not the plugin)? Might be a version incompatibility.

**Comment by htdebeer** [comment]
To add some context. this afternoon I was testing the plugin I am developing, and access to this group was going fine. But suddenly, in between two repobee executions, the same `setup` and `clone` commands stopped working.

The version is "13.6.2", revision "f508fb8a043".

**Comment by slarse** [comment]
Right, that's very odd. I'll get back to you after work (so in a couple of hours).

**Comment by htdebeer** [comment]
Awesome! 

By the way, if I use the API directly, like

```
curl "https://gitlab.tue.nl/api/v4/groups/git-for-assignments-course2020?privateversiontoken=XXXXX"
```

I do get back information about this group:

```json
{"id":3588,"web_url":"https://gitlab.tue.nl/groups/git-for-assignments-course2020","name":"git-for-assignments-course2020","path":"git-for-assignments-course2020","description":"Instance of the test \"Git for Assignments\" course","visibility":"private","share_with_group_lock":false,"require_two_factor_authentication":false,"two_factor_grace_period":48,"project_creation_level":"noone","auto_devops_enabled":null,"subgroup_creation_level":"maintainer","emails_disabled":false,"mentions_disabled":false,"lfs_enabled":true,"default_branch_protection":0,"avatar_url":null,"request_access_enabled":true,"full_name":"git-for-assignments-course2020","full_path":"git-for-assignments-course2020","created_at":"2020-07-03T08:28:38.595Z","parent_id":null,"shared_with_groups":[],"runners_token":"XXXXXXX,"projects":[],"shared_projects":[]}
```

But maybe some of these settings are incorrect.

**Comment by slarse** [comment]
That looks correct to me. I'm currently running the system tests with the same version of GitLab that you're running to see if there's some form of version incompatibility. But I don't think there is, the version that _was_ running was older, but it was still GitLab 13.

**Comment by htdebeer** [comment]
Yes.  I think something on my machine must have changed.

- I did try removing RepoBee and installing an older version because I did run the upgrade command. That did not have any effect.
- I also ran the daily updates on my operating system. Although that should have been only security updates and bugfixes, it  might have changed something system wide. What non-pure python packages might RepoBee using?

Alternatively, the gitlab instance I was testing against changed some setting somewhere. But then I would have expected not to have access via `curl` either

**Comment by slarse** [comment]
I'm not sure what your setup is like, but there might have been a rolling update. Your first request might have hit some earlier version of GitLab, and then the second one hit 13.6.2 which introduced some problem.

I'm still testing on my end, I'm having trouble with getting the system tests running for 13.6.2.

**Comment by slarse** [comment]
To be clear, it's very unlikely that something on your machine changed in between two invocations of `setup` and `clone`. I just don't see how that could happen.

System tests are passing now with 13.6.2, so it doesn't seem to be a version incompatibility.

> What non-pure python packages might RepoBee using?

None that I know of. RepoBee does not require a C-compiler, so there shouldn't be any non-pure packages. That's not to say that I'm sure, there might be some non-pure transitive dependency that has pre-built distributions for all systems I'm testing on. What OS are you on?

I'd hate for you to spend tons of time debugging this, let me know if you'd like to schedule a Skype/Teams/Zoom/whatever session to work it out.

**Comment by htdebeer** [comment]
Thanks for the offer. Monday I will try to install and run RepoBee on a different machine and see if that makes a difference. Then I will also try a different Gitlab "group" to see if that helps any. Finally, I can also try running against a different gitlab instance and see what happens. I'll report on my findings.

**Comment by slarse** [comment]
Just FYI, underlying library that RepoBee uses to interface with GitLab is called `python-gitlab`, and the code that is giving you grief right now is right here: https://github.com/repobee/repobee/blob/481c15b191829dc2c423c57b1c4ac6e50394676d/src/_repobee/ext/gitlab.py#L435-L448

If you install `python-gitlab` (`pip install python-gitlab==2.4.0`) into some environment, you can try some manual debugging. You can create an instance of the `gl` object you see in the code above like so:

```python
import gitlab

gl = gitlab.Gitlab("https://gitlab.tue.nl", private_token="<YOUR_TOKEN>")
# fetching the group is what isn't working well, so see what you get here
# this will return all groups for which the search matches a substring of their slug
matching_groups = gl.groups.list(search="git-for-assignments-course2020")
```

We currently use python-gitlab==2.4.0, but you could try the latest version python-gitlab==2.5.0 and see if that helps.

Sorry about the trouble you're having, maintaining support for multiple versions of multiple platforms is rather tricky!

**Comment by htdebeer** [comment]
I tried your python-gitlab example, and that works as expected: it returns a list of groups. Creating the list "slug_matched" also works without a problem.

**Comment by htdebeer** [comment]
I just installed repobee on another machine and configured it with the same git server, org_name, and user, but to no avail: the group with the slug cannot be found.

**Comment by slarse** [comment]
This is absolutely perplexing. I need more logging output to figure out what's going on. I'll push a new branch ASAP with ludicrous amounts of logging and give you instructions for how to install it (don't worry, it's very easy :).

**Comment by slarse** [comment]
@htdebeer I've got a slightly tweaked version of RepoBee for you with more logging and slightly different fetching of the target group. You can try it out like so (these are shell commands):

```
git clone --single-branch --branch issue/774-gitlab-logging https://github.com/slarse/repobee.git
cd repobee
python3 -m venv env
source env/bin/activate
pip install -e .
```

That should give you a virtual environment with this custom version of RepoBee. It will still access your regular config file. Then run `config verify`.

```
repobee -p gitlab config verify
```

The tweaks in this version _might_ solve the problem, because I found one thing that under very specific circumstances might cause an issue. If it doesn't, it will put some additional debug information in the log file. If you're on a Linux distro, the log file is at `~/.cache/repobee/log/repobee.log`. You might want to delete the log file before running the command to make sure that it only contains the data you want.

**Comment by htdebeer** [comment]
This works!

I also tried again with the old version, and that one still breaks. Now I am curious: What specific circumstance did cause this?

**Comment by slarse** [comment]
It was most likely a paging issue. For some reason, the GitLab plugin is using the search API to find a group by a given name (although it's perfectly possible to just fetch by path), but it only fetches a single page. There must have been more hits than a single page when searching for your group, because all I did on that branch was to fetch more pages. Which is really strange considering that name was very specific, but that must have been the reason.

Anyway, I'm gonna patch it to fetch groups directly by path instead, and that should make it more reliable.

**Comment by slarse** [comment]
I've pushed an update to the same branch, could you pull that down and verify that it still works? If it does, I'll merge it and then make a new release.

**Comment by htdebeer** [comment]
It is still working! 

A paging issue explains the sudden change in behavior. Nice find! Thanks for all your help.

**Comment by slarse** [comment]
That's great! Thanks for trying out the patches; fixing tiny details like this is super difficult without active participation from users. Expect a new release sometime tomorrow, containing both the fix in #777 and the other thing you needed with the `post_setup` hook :)

**Comment by slarse** [comment]
@htdebeer This fix is now published in v3.5.0 :)

**Comment by htdebeer** [comment]
I saw it. It works like a charm! Thanks

**Comment by slarse** [comment]
Awesome!
