### ISSUE TITLE
Add non-interactive modes for plugin install, uninstall and activation

### ISSUE THREAD

**Issue by slarse** [repobee/repobee#782]
To be able to use RepoBee in scripts, it's important that all features have non-interactive modes of execution. Currently, the plugin commands do not.

- [x] `plugin install`
    - I think this needs `--plugin-version` and `--plugin-name`
- [x] `plugin activate`
    - This one should only need `--plugin-name`
- [x] `plugin uninstall`
    - This one should only need `--plugin-name`

**Comment by slarse** [comment]
Finally, all of it should be documented in the user guide.

**Comment by slarse** [comment]
@dbosk You've now got non-interactive options for all plugin commands, see the [latest version of the docs for details](https://repobee.readthedocs.io/en/latest/plugins.html) :)

**Comment by dbosk** [comment]
Awesome! :-D Thanks a lot!
