### ISSUE TITLE
Make it possible to somehow collect and/or distribute double-blind reviews

### ISSUE THREAD

**Issue by slarse** [repobee/repobee#811]
There's currently no mechanism in place for collecting and/or distributing the double-blind reviews to the reviewed repos. I've got 3 ideas for this:

1. Automatically re-post issues in the original repos on executing reviews end
2. Make it possible for reviews check to collect the review issues into a JSON file, and add a new command for distributing issues from a JSON file (not necessarily tied into the review functionality; just posting issues based on a JSON)
3. Create a new command reviews distribute-blind-reviews that collects double-blind reviews and re-posts them in the original repos.

I like 1 and 2 most. 1 is nice because it's very simgle on the end-user. 2 is nice because it's a more generalized solution that may be applicable elsewhere.

**Comment by slarse** [comment]
To be clear: right now it's only possible to check who has performed their reviews with `reviews check`, as is the case for the normal no-blind review mode.

**Comment by rjglasse** [comment]
I vote for (2). Whilst (1) is fine for informal peer review, a teacher may wish to review the peer review process first, possibly check / grade / approve. Collecting it as a JSON file with the option to distribute later works nicely for this more advanced use case of assessed / moderated peer review.
