### ISSUE TITLE
Double-blind peer-review: failing to push to an anonymous repo can make it undeletable

### ISSUE THREAD

**Issue by amaberg** [repobee/repobee#825]
![image](https://user-images.githubusercontent.com/52538934/108203976-7b381880-7123-11eb-9fae-0f3378889fb2.png)
![image](https://user-images.githubusercontent.com/52538934/108204323-f13c7f80-7123-11eb-9a77-88460daa0eb8.png)

If a repo is created and the assign-operation then fails, you can't remove the repo created with the end-command

**Comment by slarse** [comment]
Thanks for the bug report. This is really two related issues:

1. RepoBee must check that Git is properly configured before proceeding.
2. The order of operations is a bit unfortunate. It would be better if the anonymous repo was assigned to its team _before_ pushing.

**Comment by slarse** [comment]
@amaberg Thanks for the bug report, I've fixed it now so it's always possible to end reviews, even if the review teams are missing (which was the problem here).
