### ISSUE TITLE
Config Verify Does Not Accept GitLab URL https://localhost:50443 

### ISSUE THREAD

**Issue by htdebeer** [repobee/repobee#860]
When I configure RepoBee to use my localhost as GitLab base_url (https://localhost:50443), `repobee -p gitlab config verify` gives error: 

```
GitLabAPI is verifying settings ...
Authenticating connection to https://localhost:50443...
[ERROR] PlatformError: Could not connect to https://localhost:50443, please check the URL
[ERROR] A plugin exited with an error
```

However, when I access the GitLab API directly with something like `wget "https://localhost:50443/api/v4/projects" --no-check-certificate`, GitLab does not seem to have an issue with this.

I am running GitLab locally with docker.

**Comment by htdebeer** [comment]
If I use an URL like `https://gitlab.loc.al:50443`, it is not working either. Maybe the port part of the URL is not supported?

**Comment by slarse** [comment]
Hi @htdebeer ,

There are a few things that can go wrong when using a local GitLab instance. Could you show your `docker-compose.yml` and any other relevant configuration?

If you're using RepoBee's system test configuration, it's a bit... stupidly set up, and you need to follow the instructions in the [README](https://github.com/repobee/repobee/tree/master/system_tests/gitlab#usage) carefully. I've been meaning to revise the setup to make it as simple to use as the Gitea one (essentially just run one command and you've got your GitLab instance up and running). Right now I'm really busy prepping for SIGCSE, so it will have to wait until next weekend, unfortunately.

> If I use an URL like https://gitlab.loc.al:50443, it is not working either. Maybe the port part of the URL is not supported?

Which port is GitLab serving on internally in Docker? It must be the same port.

**Comment by htdebeer** [comment]
I adapted your docker-compose.yml a bit and came up with:

```
web:
  image: 'gitlab/gitlab-ee:latest'
  restart: always
  hostname: 'localhost'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://localhost:50443'
      gitlab_rails['gitlab_shell_ssh_port'] = 50022
      nginx['listen_port'] = 443
      nginx['ssl_protocols'] = "TLSv1.1 TLSv1.2"
      nginx['redirect_http_to_https'] = true
      nginx['ssl_certificate'] = "/etc/gitlab/ssl/certificate.pem"
      nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/key.pem"
      letsencrypt['enable'] = false
  ports:
    - '50022:22'
    - '50080:80'
    - '50443:443'
  volumes:
    - '$GITLAB_HOME/config:/etc/gitlab'
    - '$GITLAB_HOME/logs:/var/log/gitlab'
    - '$GITLAB_HOME/data:/var/opt/gitlab'      
    - '$GITLAB_HOME/ssl:/etc/gitlab/ssl'
```

**Comment by htdebeer** [comment]
But my certificate was for no domain at all. I'll try setting it for "gitlab.loc.al"

**Comment by slarse** [comment]
You could have it for the `localhost` domain as well, that'd work fine.

**Comment by slarse** [comment]
I'm not sure about the mixing and matching of ports, however. I think the easiest way to get it all to work is to use the same ports internally in docker, as you use externally on your host machine. So if you use `443`, then put that everywhere. It should of course be possible to mix and match, but from personal experience it hasn't been worth the hassle.

**Comment by htdebeer** [comment]
I am also running a Canvas docker container that already uses port 443. I am not sure how to have both services use the same port.

**Comment by slarse** [comment]
That you can't. Then use `50443` for GitLab, just use it everywhere :)

**Comment by slarse** [comment]
Like this (all ports prefixed with `50` or `500`):

```
web:
  image: 'gitlab/gitlab-ee:latest'
  restart: always
  hostname: 'localhost'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://localhost:50443'
      gitlab_rails['gitlab_shell_ssh_port'] = 50022
      nginx['listen_port'] = 50443
      nginx['ssl_protocols'] = "TLSv1.1 TLSv1.2"
      nginx['redirect_http_to_https'] = true
      nginx['ssl_certificate'] = "/etc/gitlab/ssl/certificate.pem"
      nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/key.pem"
      letsencrypt['enable'] = false
  ports:
    - '50022:50022'
    - '50080:50080'
    - '50443:50443'
  volumes:
    - '$GITLAB_HOME/config:/etc/gitlab'
    - '$GITLAB_HOME/logs:/var/log/gitlab'
    - '$GITLAB_HOME/data:/var/opt/gitlab'      
    - '$GITLAB_HOME/ssl:/etc/gitlab/ssl'
```

**Comment by htdebeer** [comment]
That does not seem to make a difference. I also tried to replace all occurrences of "localhost" with "gitlab.loc.al" in the docker-compose.yml file, but that did not make a difference either.

Is there a way to get a more finegrained error message from the gitlab plugin?

**Comment by slarse** [comment]
OH, right, have you set the environment variable `REPOBEE_NO_VERIFY_SSL=true`?

**Comment by slarse** [comment]
It's a hidden option as you're not really supposed to use RepoBee without SSL verification (as it sends the token over HTTPS).

**Comment by slarse** [comment]
> Is there a way to get a more finegrained error message from the gitlab plugin?

Yes, add `--traceback` to the command and you'll see where the error comes from.

**Comment by slarse** [comment]
See the docs here about SSL verification: https://github.com/repobee/repobee/tree/master/system_tests/gitlab#disable-ssl-verification

**Comment by htdebeer** [comment]
Disabling SSL verifying with `REPOBEE_NO_VERIFY_SSL=true` did the trick! 

Thanks for your help!

**Comment by slarse** [comment]
Awesome, glad I could help :)

**Comment by htdebeer** [comment]
To add, to run the `repobee repos setup` command, I also had to disable SSL check for Git using `git config --global http.sslverify false`. Do not use this in a production environment, though!

**Comment by slarse** [comment]
Correct, that's also in the docs here: https://github.com/repobee/repobee/tree/master/system_tests/gitlab#disable-ssl-verification

It's somewhat hidden away because I don't want to accidentally have non-developers do that to "fix a problem". In practice, RepoBee cannot be used without SSL, it's just for development.
