### ISSUE TITLE
Add hint about how to smoothly create a local config file

### ISSUE THREAD

**Issue by slarse** [repobee/repobee#861]
Right now, the [docs on local config files](https://docs.repobee.org/en/stable/getting_started.html?highlight=local#local-config-files) just say that you can create a local config file called `repobee.ini`, that takes precedence over the global config file. There's no mention of how to do this. The simplest way is like this:

```
repobee --config-file repobee.ini config wizard
```

This _is_ noted in the [Docker docs](https://docs.repobee.org/en/stable/docker.html#id4), but it should definitely be mentioned in the config section of the user guide as well.

**Comment by slarse** [comment]
@htdebeer this might be of interest to you if you need to bounce between your local environment and your school's actual GitLab instance.

**Comment by htdebeer** [comment]
Nice tip! I did this, but at the end of the wizard, I got the message "`Configuration file written to /home/huub/.config/repobee/config.ini`". The "`repobee.ini`" file in my current directory did get written, though

**Comment by slarse** [comment]
Oops, that message is hard-coded! Thanks for pointing it out :)
