### ISSUE TITLE
Extended syntax of students file

### ISSUE THREAD

**Issue by davbeek** [repobee/repobee#880]
After having used GitHub Classroom last year for my course of about 160 students, I intend to switch to Repobee this year. After some preliminary tests, repobee appears to satisfy my needs and has a big advantage in that I can use GitLab instead of GitHub.

I have, however, encountered one problem. TUE students use their 8 digits TUE login id also for gitlab, which means that for a group of two students working on an assignment task1, I end up with an unintuitive repo name of the form 20173795-20172456-task1. 

Each student group also has a group id, such as 412. This groupId is useful in many ways, such as publishing group grades without compromizing privacy. What I would like to see as a repo name is then something like 412-JohnWilliams-MaryBrooks-task1.

This would require extending the syntax of the student file for example as follows:
groupId: studentLogIn1:studentName1 studentLogIn2:studentName2 ...,
where groupId: would be optional.

To achieve this, I see three possibilities:
1) I write a Python script, to rename the local student repos after having cloned them.
2) The repobee teams extends Repobee to extend the syntax of the students file.
3) I ask a programmer to extend Repobee. Although I do have the means for this (https://boost.tue.nl/projects/ict-tools-to-support-tpil-in-project-groups/), it does not seem the most efficient way to achieve my goal.

The first option is of course always possible. The second option would be preferable from a usability perspective, making Repobee more user friendly and more accessible for a larger audience. What are your thoughts on this? If adding student names would be too much work, just extending the students file with group ids would already be a big help.

**Comment by slarse** [comment]
Hi @davbeek,

Thanks for the very elaborate problem description!

While most of what you need can already be achieved with some relatively simple plugins, I think it's about time this functionality is added to RepoBee itself (so, option 2). This is not the first time I've gotten the request.

I will think about the best way to do this and get back to you. I think a standardized format (e.g. YAML) for the students file would be better than a custom one. Then, further extensions could also be made without too much effort.

I'll get back to you once I've put some thought into this!

**Comment by davbeek** [comment]
Sounds good, thanks for taking this into consideration.

**Comment by slarse** [comment]
@davbeek Finally coming back around to this problem :). It's not a super easy problem to solve, but it is doable.

How high of a priority is this to you, and when would you need it to be done?

**Comment by davbeek** [comment]
It would be very nice to have, but I could run my course based on Repobee this year in September without it. 

I would need it for my course that starts in the first week of September, so perhaps the last week of August to leave so room for testing. If it would not be ready by then, it would be useful again one year later: September 2022.

**Comment by davbeek** [comment]
If you would start this, it would be useful to keep Huub de Beer in the loop, so that he can provide the output of his [plugin for Canvas](https://github.com/htdebeer-tue/repobee-canvas) in the new format.

**Comment by slarse** [comment]
I would like to, at the very least, have a preview version of this in RepoBee 3.7 which must be released before the next term

**Comment by slarse** [comment]
BTW, "preview version" means that it needs to be enabled with a feature flag (currently works by setting an environment variable), so I'm free to make breaking changes if I feel it's necessary.

**Comment by davbeek** [comment]
Sounds great, would make use of Repobee a lot more user-friendly. Looking forward to it, but if it doesn't work in time, no problem!

**Comment by davbeek** [comment]
I don't know if this would simplify your work, but it would already be a big help if I could specify for each repo a groupID for the repo name, so that each student repo could get a groupID as name, instead of the concatenation of the student IDs.

**Comment by slarse** [comment]
Hi @davbeek,

> so that each student repo could get a groupID as name, instead of the concatenation of the student IDs.

You could technically do this with a plugin, as the name of student repos can be overridden by implementing the [`generate_repo_name` hook function](https://docs.repobee.org/en/stable/repobee_plug/code.html#repobee_plug._corehooks.generate_repo_name).

But I'll take it into consideration when tinkering with the extended syntax, I hope to get it done this month (August) :)

**Comment by davbeek** [comment]
> You could technically do this with a plugin, as the name of student repos can be overridden by implementing the generate_repo_name hook function.

Good to know. I might ask JingJing to do this, in case you work on the extended syntax takes longer than expected.

**Comment by slarse** [comment]
I'm looking at it this week. I have a few different ideas. I'll let you know what I come up with by the weekend.

**Comment by slarse** [comment]
Hi @davbeek,

I decided to include this functionality directly into RepoBee, and to that end created a parser for a tiny subset of YAML (see [YAMLiny](https://github.com/slarse/YAMLiny)). It took a tad bit longer than I expected (as with all things), so I'll delay the release of RepoBee 3.7 untill (hopefully) tomorrow, then including this extended syntax as a built-in plugin.

Eventually, this will just be built-in without the need for a plugin, but I don't want to lock in the exact functionality until it's been battle-tested :)

**Comment by davbeek** [comment]
Thanks @slarse, this comes perfectly in time for the start of my course next week!

**Comment by slarse** [comment]
@davbeek You're welcome!

Note also that RepoBee 3.7.0 is out, which includes the `studentsyml` plugin. So you need to upgrade to the latest version (`repobee manage upgrade`) and activate the plugin (`repobee plugin activate --plugin-name studentsyml`) to activate the extended syntax for the students file :)

**Comment by davbeek** [comment]
Thanks for the tip and instructions :-)
