### ISSUE TITLE
Make it possible to clone repositories into flat directory structure

### ISSUE THREAD

**Issue by davbeek** [repobee/repobee#881]
When cloning student repos to my local computer, I end up with each student repo in its own private folder, because Repobee creates for each student group a separate folder. For instance, I have a task task1 and the following students file:
20171234 20171256
20176543 20175890

If I then create the student repos and clone them, I end up with two folders:
- 20171234-20171256, which contains a single repo: 20171234-20171256-task1
- 20176543-20175890, which contains a single repo: 20176543-20175890-task1

I would like instead to simply get two repos in the same folder:
20171234-20171256-task1 and 20176543-20175890-task1

The additional student group folders serve no purpose, since the group name is already encoded in the repo name. Even in the case of multiple tasks per student group, alphabetical sorting of the repos would already group the repos of each student group together.

**Comment by slarse** [comment]
Hi @davbeek,

The subdirectories serve the purpose of avoiding name collisions on platforms that support nested namespaces (currently only GitLab). There's nothing stopping students from creating identically named repositories on GitLab, and when running RepoBee with `--discover-repos`, it can cause name collisions in a flat structure.

It's also been requested by multiple users to get some structure in the cloned directories.

What could be done here is to add an option (e.g. `--flat`) to clone without directory nesting. WDYT?

**Comment by davbeek** [comment]
> What could be done here is to add an option (e.g. --flat) to clone without directory nesting.

That would be really great!

**Comment by slarse** [comment]
I changed the title of the issue to reflect the suggested solution :)

Off the top of my head, this feature should be very straightforward to add. I'll give it a look as soon as I can.

**Comment by slarse** [comment]
Totally forgot about this feature, but working on it now.

I think it would be good to open this up for other directory layouts in the future. Aside from the default hierarchical layout based on student team and a flat layout, I could also imagine that it would be useful to clone in a hierarchical layout by task. I.e. something like this:

```
Hierarchical by student team

alice 
   |---- alice-task-1
   |---- alice-task-2
bob
   |---- bob-task-1
   |---- bob-task-2

Hierarchical by task

task-1
   |---- alice-task-1
   |---- bob-task-1
task-2
   |---- alice-task-2
   |---- bob-task-2
```

In that sense, I think the command line option should be something along the lines of `--directory-layout [flat|by-team|by-task]`, with a default of `by-team`.
