### ISSUE TITLE
Gitlab when "Default branch protection" is configured on the instance, all student repo's cannot push to master

### ISSUE THREAD

**Issue by sakehl** [repobee/repobee#896]
In Gitlab, it is possible to set "Default branch protection" to "Fully protected" (or something similar), see [here](https://docs.gitlab.com/ee/user/admin_area/settings/visibility_and_access_controls.html#default-branch-protection) in the admin area. This means that any newly created group automatically set their branch protection to "Fully protected".

E.g. see:
![image](https://user-images.githubusercontent.com/19996620/115834521-9c640080-a415-11eb-8792-7163ccf6376c.png)
After setting up the repos, with a command like `repobee -p gitlab repos setup --assignments ha-0 --students-file test-students.txt`

This leads to having all the students having the master branch protected in their own made repository, e.g.:
![image](https://user-images.githubusercontent.com/19996620/115834830-ebaa3100-a415-11eb-818b-79ac26c2cc1a.png)

Which in our case is very unwanted.

We thought this was solved by setting our group (that is specified as `org_name`) with the "Default branch protection" setting to "Not protected", but this was not the case. I suspect the students newly created groups take over the default setting from the whole Gitlab, and not the parent group.

<details><summary>I've written the script bellow, which fixed all the instances using the python gitlab API, so probably something similar can be used in solving this issue.</summary>
<p>

This script deletes the protected setting for the master branch, and recreates the protected setting, were developers have push and merge access. But developers (students) cannot delete or force push to this branch now. 
```python
import gitlab

token = "editedawaytoken"

gl = gitlab.Gitlab('https://gitlab.mysite.com', private_token=token)

group = gl.groups.get('org_name#replace correct org name')
subgroups =  group.subgroups.list(all=True)
for sub in subgroups:
  real_group = gl.groups.get(sub.id, lazy=True)
  real_group.default_branch_protection = 0
  real_group.save()
  projects = real_group.projects.list(all=True)
  for project in projects:
    real_project = gl.projects.get(project.id)
    branches = real_project.protectedbranches.list(all=True)
    for branch in branches:
      if branch.name == 'master':
        master_branch = real_project.protectedbranches.get('master')
        master_branch.delete()
    real_project.protectedbranches.create({
        'name': 'master',
        'push_access_level': gitlab.DEVELOPER_ACCESS,
        'merge_access_level': gitlab.DEVELOPER_ACCESS,
        'allow_force_push': False
    })
    real_project.save()
```

</p>
</details>

# Solution
I'm not sure what a correct solution would be since I could imagine some people indeed do want students to have protected branches configured, but I think in general you would not want this. Some ideas for different solutions:
1. Student repositories by default will not have protected branches, the created student's groups have their default branch protection setting turned off, something which can be done with the python gitlab API like:
```python
real_group.default_branch_protection = 0
real_group.save()
```
2.  When the admin setting for branch protecting is on, the user will get a prompt (or warning) when using Repobee to make new studfent repositories, forcing the user to choose to set branch protecting on or off. (in this case it would be best to also give an option to fix this afterwards if they realize they do/don't want branch protection).
3. The setting is copied from the configured `org_name`. If branch protection is on, a similar warning or prompt as suggested above is given.

Maybe you have some thoughts on these solutions?

**Comment by slarse** [comment]
> I'm not sure what a correct solution would be since I could imagine some people indeed do want students to have protected branches configured, but I think in general you would not want this.

I also think that in general, this is not desirable. I'd like RepoBee's behavior to be as consistent across platforms as possible, with GitHub as the reference. And on GitHub, this behavior does not exist, the default branch is always unprotected (for better or for worse). Therefore, I would favor option 1. at the moment, and I consider this current behavior a bug.

**Comment by slarse** [comment]
I will get on fixing this right away.

**Comment by slarse** [comment]
@sakehl I've implemented a fix using option 1). Thanks for the very thorough description of the problem, made it very easy to fix it.

You're also correct that, somewhat curiously, new groups inherit the global setting, as opposed to the parent group's setting, see [the API docs](https://docs.gitlab.com/ee/api/groups.html#new-group).

**Comment by sakehl** [comment]
@slarse thanks a lot for the quick look and fix for this. This looks great. I'll test it when I'll set up my new assignments, but I'm pretty sure this should fix it.

**Comment by slarse** [comment]
You're welcome! This seemed like kind of a showstopper for the GitLab functionality, so I thought it was a high priority to fix :)
