### ISSUE TITLE
Allow config inheritance by path that's relative to the config file.

### ISSUE THREAD

**Issue by slarse** [repobee/repobee#920]
It makes sense that the parent path in the config file should be able to use a path that's relative to the config file. Currently that's not possible, it will be relative to the working directory, which imo is rather confusing.

@htdebeer-tue What do you think for your use case? To me it would be most intuitive if the path was relative to the file it's written in.

**Comment by htdebeer-tue** [comment]
Certainly!

I do not think we can assume that the directory the config file is in always matches the working directory. When it does not, the parent path would be very confusing to reason about. Moreover, calling repobee from a different directory would no longer work as expected either.

**Comment by slarse** [comment]
Thanks for the input!

The parent path is now either a) absolute, or b) resolved as a relative path based on the path to the config it's defined in. With that, inheritance is now implemented in RepoBee, but I will change some of the details of how it works as I'm not quite happy with the "cleanliness" of it. The implementation is slightly messy and unintuitive, and lacks any meaningful error handling.

**Comment by htdebeer-tue** [comment]
Thanks!

Once this academic year has ended, I will look into using this feature to finish my Canvas plugin.

**Comment by slarse** [comment]
When does your academic year end?

I think it would be best to ensure that this functionality works well for your use case before it's released into the wild. I'm thinking that it should based on the use case scenario you provided earlier, but there's always the chance I've missed something.

**Comment by htdebeer-tue** [comment]
I hope to finish the last grading for this academic year on July 7th. After that I have a week or so to work on repobee+canvas. Then I will go on vacation for a couple of weeks. Halfway August I will continue working on this again. This gives us enough time to explore your solution?

**Comment by slarse** [comment]
That should be all well and good! I'll make sure it's polished and good to go by the beginning of July, and then we can try it out there. The outside surface area of the config inheritance is pretty small, so it shouldn't take much time to evaluate if it works for you.

I'll make a beta release of RepoBee 3.7 available by then so you can easily install it. I think that once we're satisfied with the config inheritance and perhaps other minor features required by repobee-canvas, it's time to release 3.7.
