### ISSUE TITLE
Upgrade to v3.7.0 not happy with existing plugins

### ISSUE THREAD

**Issue by rjglasse** [repobee/repobee#960]
To upgrade from v3.5.0 I re-ran the installer script for Zsh from the homepage (https://repobee.org/). Install script seems to run fine. I get this feedback for a version request:

```zsh
% repobee -v          
exception was raised before pre-initialization was complete. This is usually due to incorrect settings. Try running the `verify-settings` command and see if the problem can be resolved. If all fails, please open an issue at https://github.com/repobee/repobee/issues/new and supply the stack trace below.
[ERROR] PluginLoadError: failed to load plugin module sanitizer
[ERROR] RepoBee exited unexpectedly. Please visit the FAQ to try to resolve the problem: https://repobee.readthedocs.io/en/stable/faq.html
```

Running `verify-settings` did not work either (same feedback as above).

Removing the all plugins from block from `~/.repobee/installed_plugins.json` resolved the issue for me:

```json
"_metainfo": {
        "active_plugins": [
            "sanitizer",
            "csvgrades"
        ]
    }
```

Is it best to nuke the .repobee folder before upgrading? Perhaps we need to modify the homepage to include advice for upgrading.

Cheers!

**Comment by rjglasse** [comment]
Note, I probably should have tried `repobee manage upgrade` first, but I guess others might make this blunder :-)

**Comment by slarse** [comment]
While you're not supposed to use the install script to upgrade, it's intended to be a last resort to fix a failing installation. So, it should nuke all preexisting state in the install directory, so there might be a bug there.

Of course `repobee manage upgrade` is the intended way to upgrade, but perhaps that should be more front-and-center on the website and the user guide (in fact, I think it isn't even mentioned in the user guide).

**Comment by slarse** [comment]
On a side note, the [FAQ](https://docs.repobee.org/en/stable/faq.html#repobee-crashes) has a bunch of tips for how to fix a broken install.
