### ISSUE TITLE
Remove the `util` module

### ISSUE THREAD

**Issue by slarse** [repobee/repobee#979]
Having a module named `util` is a bad smell, it just screams "I couldn't be bothered to think".

The [`util` module](https://github.com/repobee/repobee/blob/master/src/_repobee/util.py) should be removed. Any unused functions should be removed, and any used functions should be moved to more appropriate modules.

Most functions should probably move to the [`fileutil` module](https://github.com/repobee/repobee/blob/master/src/_repobee/fileutil.py). This will also entail creating a `test_fileutils` module at `tests/unittests/repobee/test_fileutil.py` and migrating test functions from `tests/unittests/repobee/test_util.py`.

There will also be a need to fiddle with imports throughout the production code.

**Comment by slarse** [comment]
@algomaster99 This is a good first issue for you!

**Comment by algomaster99** [comment]
@slarse I will be on it as soon as possible :)
